services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: discover
      POSTGRES_PASSWORD: discover
      POSTGRES_DB: discover
    volumes:
      - discover_postgres_data:/var/lib/postgresql/data

volumes:
  discover_postgres_data:
